name: "Release"

on:
  release:
    types:
      - published
permissions:
  contents: write
  packages: write


jobs:
  release:
    name: Prepare release
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Create zip file
        run: |
          cd custom_components/ha_log_debugger
          zip -r ../../ha_log_debugger.zip . -x "__pycache__/*" "*.pyc" "*.pyo"

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ha_log_debugger.zip
          asset_name: ha_log_debugger.zip
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
